### ISSUE TITLE
[Fzf-lua] Difficulty in setting up a keymap

### ISSUE THREAD

**Issue by Balssh** [nix-community/nixvim#2425] opened 2024-10-16 14:00 UTC
Hi, I'm using the following configuration of fzf-lua in nixvim:
```nix
{
  programs.nixvim = {
    plugins = {
      fzf-lua = {
        enable = true;
        profile = "fzf-native";
        settings = {
          fzf_opts = {
            "--cycle" = "";
          };
        };
        keymaps = {
          "<leader>sg" = "live_grep";
          "<leader>sf" = "files";
          "<leader>sr" = "resume";
          "<leader><leader>" = "buffers";
          "<leader>sw" = "grep_cword";
          "<leader>s." = "oldfiles";
        };
        luaConfig.post = "require('fzf-lua').register_ui_select()";
      };
    };
  };
}
```

What I'm trying to add is the following part of a config (written in lua):
```lua
require('fzf-lua').setup {
        keymap = {
          fzf = {
            false, -- do not inherit from defaults
            ['ctrl-d'] = 'preview-half-page-down',
            ['ctrl-u'] = 'preview-half-page-up',
          },
        },
      }
```

Tried several ways but keep getting various errors.

**Comment by MattSturgeon** [comment] 2024-10-16 14:08
At the most fundamental level, you can always translate any lua passed to `setup` as a nix attrset assigned to `settings`:

```nix
settings = {
  keymap.fzf = {
    __unkeyed-1 = false; # do not inherit from defaults
    ctrl-d = "preview-half-page-down";
    ctrl-u = "preview-half-page-up";
  };
}
```

However you'd have to check what is produced using `nixvim-print-init`.

In particular I'm unsure how our `plugins.fzf-lua.keymaps` option will interact with the `keymap.fzf` table and/or if passing `false` will work as intended or if we'll define extra keymaps...

You may find the docs ([plugin](https://nix-community.github.io/nixvim/plugins/fzf-lua/index.html), [settings](https://nix-community.github.io/nixvim/plugins/fzf-lua/settings.html), [keymaps option](https://nix-community.github.io/nixvim/plugins/fzf-lua/keymaps/index.html), etc) and [module source code](https://github.com/nix-community/nixvim/blob/main/plugins/by-name/fzf-lua/default.nix) useful for any further investigation :slightly_smiling_face:

**Comment by Balssh** [comment] 2024-10-16 19:46
Thanks for the reply! I've already dug through those docs before opening this issue and I think there needs to be some tweaking to the plugin as no mater what combination of settings.keymaps.fzf.<option> I do it spits something along this line:
```
 The option `home-manager.users.balssh.programs.nixvim.plugins.fzf-lua.keymaps.fzf.__unkeyed-1' does not exis…
┃        - In `/nix/store/4hfjhyil2a3va3vr36pg94iqymvnsgz8-source/modules/home/common/nvim/plugins/fuzzy.nix': false
```
```
The option `home-manager.users.balssh.programs.nixvim.plugins.fzf-lua.keymaps.fzf.ctrl-d' does not exist. Definition values:
       - In `/nix/store/m1vh7j046jvb5787dkwppqx7im630469-source/modules/home/common/nvim/plugins/fuzzy.nix': "preview-half-page-down"
```
Also, `nixvim-print-init`'s keymaps looks like:
![image](https://github.com/user-attachments/assets/2a18435d-a5e5-40b0-ac7c-f58ee4ae8d95)
while I believe the it should've been resembling more this:
![image](https://github.com/user-attachments/assets/52702085-c0e7-4f00-a60a-e5b492cb7b63)

All in all I think I can hack this by passing a full on lua config for this plugin (which I might) until the keymap is sorted out.

**Comment by MattSturgeon** [comment] 2024-10-18 20:08
> no mater what combination of `settings.keymaps.fzf`. I do it spits something along this line:
> 
> ```
>  The option `home-manager.users.balssh.programs.nixvim.plugins.fzf-lua.keymaps.fzf.__unkeyed-1' does not exis…
> ┃        - In `/nix/store/4hfjhyil2a3va3vr36pg94iqymvnsgz8-source/modules/home/common/nvim/plugins/fuzzy.nix': false
> ```
> 
> ```
> The option `home-manager.users.balssh.programs.nixvim.plugins.fzf-lua.keymaps.fzf.ctrl-d' does not exist. Definition values:
>        - In `/nix/store/m1vh7j046jvb5787dkwppqx7im630469-source/modules/home/common/nvim/plugins/fuzzy.nix': "preview-half-page-down"
> ```

You mention `settings.keymaps.fzf`, however based on the lua you [quoted](https://github.com/nix-community/nixvim/issues/2425#issue-2591995595) before that should be `settings.keymap.fzf` (no `s`).

Also those errors are relating to `plugins.fzf-lua.keymaps` which is an **entirely separate option** to `plugins.fzf-lua.settings`. The `keymaps` option is a nixvim-specific custom option for us to generate some mappings for you, while the `settings` option is configuration to be passed to `require('fzf-lua').setup()`.

> Also, `nixvim-print-init`'s keymaps looks like: ![image](https://private-user-images.githubusercontent.com/82440615/377207785-2a18435d-a5e5-40b0-ac7c-f58ee4ae8d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyODE4NjYsIm5iZiI6MTcyOTI4MTU2NiwicGF0aCI6Ii84MjQ0MDYxNS8zNzcyMDc3ODUtMmExODQzNWQtYTVlNS00MGIwLWFjN2MtZjU4ZWU0YWU4ZDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE5NTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MzA5ZDBiZWFjMTM4NDc5YTdhOWM4OWZlYjZkMTgxMmFjZDQ5MGM0Zjg3ZTA0M2QxZjhiNzJjNDQwYjk4YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BzsHk9aXB6_Jt2-A9RNbArJ7_O_DVcPjc4_-ia2ciPI) while I believe the it should've been resembling more this: ![image](https://private-user-images.githubusercontent.com/82440615/377208658-52702085-c0e7-4f00-a60a-e5b492cb7b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyODE4NjYsIm5iZiI6MTcyOTI4MTU2NiwicGF0aCI6Ii84MjQ0MDYxNS8zNzcyMDg2NTgtNTI3MDIwODUtYzBlNy00ZjAwLWE2MGEtZTViNDkyY2I3YjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE5NTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMDk5N2EyNWQ1NjdkZTgwMzY1NTYyZmY4YjlmNGFlNzIwM2VlMzhiNTg0NzVmYWRlYmQyMWVlNzM3NmExNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DuWyt_UMft5jQUljxER4Hm0K4M8aAyOfe-tmLUhRxvU)

It sounds to me like our `keymaps` option isn't designed to use the fzf-lua's `keymap.fzf` setting. Perhaps our `keymaps` option is outdated and/or incorrect? Regardless, you should still be able to do what you want with the `settings` option without having to resort to using extra config lines.

**Comment by Balssh** [comment] 2024-10-19 09:26
Well that is embarrassing from my part. Indeed I kept confusing `keymaps` with `settings.keymap`. Sorry for wasting your time and thanks for the help. I'll leave below the snippet that works, if anyone happens to be as blind as me in the future:
```nix
{
  programs.nixvim = {
    plugins = {
      fzf-lua = {
        enable = true;
        profile = "fzf-native";
        settings = {
          fzf_opts = {
            "--cycle" = "";
          };
          keymap.fzf = {
            __unkeyed-1 = false; # do not inherit from defaults
            ctrl-d = "preview-half-page-down";
            ctrl-u = "preview-half-page-up";
          };
        };
        keymaps = {
          "<leader>sg" = "live_grep";
          "<leader>sf" = "files";
          "<leader>sr" = "resume";
          "<leader><leader>" = "buffers";
          "<leader>sw" = "grep_cword";
          "<leader>s." = "oldfiles";
        };
        luaConfig.post = "require('fzf-lua').register_ui_select()";
      };
    };
  };
}
```

**Closed** 2024-10-19 09:26 UTC
