### ISSUE TITLE
Lua keymaps and keymaps without actions

### ISSUE THREAD

**Issue by MaxIDgis** [nix-community/nixvim#620] opened 2023-10-03 13:06 UTC
**Nixpkgs channel**: unstable
**Home-manager version**: master branch and home.stateVersion = "23.05";

## Description
Since https://github.com/nix-community/nixvim/pull/605 I am unable to define keymaps with only a description and no action.
I used this to get nice prefixes in which-key. Instead it results in the following error:
```
Error detected while processing /home/maxh/.config/nvim/init.lua:                                                                    
E5113: Error while calling lua chunk: vim/keymap.lua:0: rhs: expected string|function, got nil                                       
stack traceback:                                                                                                                     
        [C]: in function 'error'                                                                                                     
        vim/shared.lua: in function 'validate'                                                                                       
        vim/keymap.lua: in function 'set'                                                                                            
        /home/maxh/.config/nvim/init.lua:248: in main chunk                                                                          
Press ENTER or type command to continue  
```
In addition, keymaps that use actions defined in lua give the following error:
```
Error detected while processing /home/maxh/.config/nvim/init.lua:                                                                    
E5113: Error while calling lua chunk: vim/keymap.lua:0: rhs: expected string|function, got boolean                                   
stack traceback:                                                                                                                     
        [C]: in function 'error'                                                                                                     
        vim/shared.lua: in function 'validate'                                                                                       
        vim/keymap.lua: in function 'set'                                                                                            
        /home/maxh/.config/nvim/init.lua:248: in main chunk                                                                          
Press ENTER or type command to continue                                                                         
````

## Config
First keymap for the first error, second keymap for the second error:
```
programs.nixvim.enable = true;
programs.nixvim.plugins = {
   mini = {
      enable = true;
      modules = {
         bufremove = {};
      };
   }
};
programs.nixvim.keymaps = [
    { key = "<leader>f"; options.desc = "File"; }
    { key = "<leader>bk"; action = "MiniBufremove.delete(0)"; lua = true; options.desc = "Kill buffer"; }
];
```
For the second keymap the following does work:
```
programs.nixvim.keymaps = [
   { key = "<leader>bk"; action = "<CMD>lua MiniBufremove.delete(0)<CR>"; options.desc = "Kill buffer"; }
];
```

**Comment by GaetanLepage** [comment] 2023-10-03 14:53
Hello !

For the `lua` issue, this is indeed not normal. I was not able to reproduce your bug.
Can you try to update nixvim to the latest version please ?

For the "keymap without action" scenario you are right. It is no more possible.
This is intended in the new design.
To provide a description without defining the mapping itself, you should now use [`plugins.which-key.registrations`](https://nix-community.github.io/nixvim/plugins/which-key/index.html#pluginswhich-keyregistrations).
This is much more natural as it imitates what you would do in lua to do the same thing.

**Comment by MaxIDgis** [comment] 2023-10-09 06:23
Hello!
Apologies for the delay.

I'll register the which-key definitions in the intended way ;)

As for the other issue,
```
keymaps = [
  {
    key = "<leader>tt";
    action = "function() print('hello') end";
    lua = true;
    options.desc = "Test"
  }
];
```
works for me as well.

I have updated nixvim to the latest version and my lua keymap issue still persists on my machine.

Calling MiniBufRemove.delete(0) from the command palette works as expected, but including it as a lua keybind breaks my config. The non-lua version works fine.

**Comment by GaetanLepage** [comment] 2023-10-09 06:28
Thanks for your reply.
Your issue with `MiniBufRemove.delete(0)` has nothing to do with nixvim actually.

When you bind a lua action, you have to provide a **function**, not a call.

```lua
# valid (my_func is a function)
vim.keymap.set('n', '<leader>tt', 'my_func', {})

# invalid, here we provide a **call** to my_func
vim.keymap.set('n', '<leader>tt', 'my_func()', {})

# If my_func expect some parameter, you have to wrap it in a parameter-less function:
vim.keymap.set('n', '<leader>tt', 'function() my_func(42) end', {})
```

**Comment by GaetanLepage** [comment] 2023-10-09 13:56
I will close this as I guess that there are no more nixvim-related bugs.
Feel free to re-open if I missed something :)

**Closed by GaetanLepage** 2023-10-09 13:56 UTC
Labels: bug

**Comment by MaxIDgis** [comment] 2023-10-11 05:51
This indeed solves my problem.
Thank you very much for your help and patience!
