### ISSUE TITLE
README: Link to Installation docs is incorrect

### ISSUE THREAD

**Issue by Vartroc** [nix-community/nixvim#2142] opened 2024-09-01 14:17 UTC
- [X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When I click on the link in the Installation section, I get to a weird site that says 'Pagenot found' above the tab but still displays some information. My guess is that it is an outdated link.

**Comment by Vartroc** [comment] 2024-09-01 14:20
Sorry, I forgot to change the tag, now I can't find the location where to change it

**Comment by Vartroc** [comment] 2024-09-01 14:23
https://github.com/nix-community/nixvim/blob/main/README.md#L92
Location I mean

**Comment by Vartroc** [comment] 2024-09-01 14:25
When I open something:
![Screenshot_20240901_162416_Brave.jpg](https://github.com/user-attachments/assets/737cfaa2-35eb-41c8-83c0-956fe0abc550)

When I click on something:
![Screenshot_20240901_162409_Brave.jpg](https://github.com/user-attachments/assets/a021681d-fb15-42ed-950a-8018794e6dbe)

**Comment by MattSturgeon** [comment] 2024-09-01 18:03
Duplicate of https://github.com/nix-community/nixvim/issues/1625

**Comment by MattSturgeon** [comment] 2024-09-01 19:02
My mistake, #1625 is about the links _in_ the docs, while this is about a link _to_ the docs.

**Closed** 2024-09-01 19:31 UTC
Labels: bug, documentation, duplicate
