### ISSUE TITLE
[PLUGIN REQUEST] CopilotChat.nvim

### ISSUE THREAD

**Issue by Industrial** [nix-community/nixvim#1425] opened 2024-04-16 06:46 UTC
| Field    | Description |
|----------|-------------|
| Plugin   | `CopilotChat.nvim`  | 
| Homepage | `https://github.com/CopilotC-Nvim/CopilotChat.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information
The missing piece to copilot powered editing in vim! I still have to fire up VSCode only for this feature..

**Comment by MikaelFangel** [comment] 2024-05-14 07:11
I have added a PR in Nixpkgs to add the plugin:
https://github.com/NixOS/nixpkgs/pull/310697

**Comment by PowerUser64** [comment] 2024-05-31 21:59
Duplicate of #992

**Closed** 2024-05-31 22:34 UTC
Labels: enhancement
