### ISSUE TITLE
$VIMRUNTIME not set on NixOS

### ISSUE THREAD

**Issue by volkswagenfeature** [nix-community/nixvim#79] opened 2022-12-02 04:55 UTC
**Plugin affected**: N/A
**Nixpkgs channel**: 22.05 (github:NixOS/nixpkgs/0faaf0a9bb6dedb69bfd43ac06fb27fadc476c51)
**Home-manager version**: N/A

## Description
`E484: Can't open file /etc/nvim/syntax/syntax.vim` on startup, and others when opened in vim mode. No help files present. running `:help` returns `E433: No tags file` and `E149: Sorry, no help for help.txt` 

I beleive this is related to `:echo $VIMRUNTIME` returning `/etc/nvim` instead of something more sensible like 
`/nix/store/7vaavg9j2q0xg6w1wr42hir1vbsh2b90-neovim-0.7.0/share/nvim/runtime`

Seems like it might be the same bug from #40 and #45?

## Config
```
programs.nixvim={
    enable = true;
    #vimAlias = false;
    #viAlias = false;
    options = {
        nocompatible = true;

        # Default indenting
        smartindent = true;
        tabstop = 4;
        shiftwidth = 4;
        expandtab = true;
        softtabstop = 4;

        number = true;
        ruler  = true;
        hlsearch = true;
        syntax = true;
        
        background = "dark";
        colorcolumn = 80;



      };
  }
```

**Comment by volkswagenfeature** [comment] 2022-12-02 05:02
A workaround I'm using at the moment is just to make a symlink where it expects to see the folder:

`sudo ln -s /nix/store/7vaavg9j2q0xg6w1wr42hir1vbsh2b90-neovim-0.7.0/share/nvim/runtime /etc/nvim`

I'm sure there's a more sensible way to get the hash in the nix store path, but since I'm new to Nix I've just been using `file $(which nvim)` to find out where it's located.

**Comment by pta2002** [comment] 2022-12-08 17:27
I'll take a look at this, but now that 21.11 is released (and AFAICT it works there), maybe it's not worth patching in the support for older versions. If there's enough demand I'll add something for this though.

**Comment by volkswagenfeature** [comment] 2022-12-19 17:33
Yeah, mostly opened for continuing tracking on the `$VIMRUNTIME` issue that's been following us... I actually suspect it's still present in 21.11 some situations. I've had it crop up since upgrading, but I haven't yet taken the time to make it reproducible, so it might be my imagination.

**Comment by JulienMalka** [comment] 2023-01-05 23:20
I can confirm that I've also been having this issue on NixOS 22.11

**Comment by Church-** [comment] 2023-01-06 06:52
Same here, also having this issue.

**Comment by pta2002** [comment] 2023-01-06 11:28
Ah damn it, thought it had gone away! Can you share a basic config @JulienMalka and @Church-? Also, what module are you using to set up nixvim?

**Comment by Church-** [comment] 2023-01-06 19:38
Hey there, my config is
```
{ pkgs, config, ... }:

{
  programs = {
    nixvim = {
      enable = true;
      viAlias = true;
      vimAlias = true;
      options = {
        termguicolors = true;
        background = "dark";
        ignorecase = true;
        swapfile = false;
        showmatch = true;
        hlsearch = true;
        wildmode = [ "longest" "list" ];
        expandtab = true;
        tabstop = 4;
        shiftwidth = 4;
      };
      extraConfigVim = ''
        set completeopt=menuone,noinsert,noselect              
        set shortmess+=c                                       
        set whichwrap+=<,>,h,l,[,]                             
        au BufRead,BufNewFile *.md setlocal textwidth=80       
        au BufRead,BufNewFile *.yaml setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.yml setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.sls setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.sh setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.nix setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.js setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.ts setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.lua setlocal textwidth=80 shiftwidth=2 cc=80                                                  
        au BufRead,BufNewFile *.py setlocal textwidth=80 shiftwidth=4 cc=88                                                   
        au BufRead,BufNewFile *.rs setlocal textwidth=80 shiftwidth=4 cc=80
        au BufRead,BufNewFile *.c setlocal textwidth=80 shiftwidth=4 cc=80
        au BufRead,BufNewFile *.go setlocal textwidth=80 shiftwidth=4 cc=80
        au BufWrite *.rs :Autoformat
        au BufWrite *.nix :Autoformat
      '';
      plugins = {
        lsp = {
          enable = true;
          servers = {
            rnix-lsp = { enable = true; };
            rust-analyzer = { enable = true; };
          };
        };
      };
    };
  };
}
```

**Comment by volkswagenfeature** [comment] 2023-01-22 15:18
Changed name to reflect that this is no longer a 22.05 issue. I also had the same thing pop up on 22.11 on my WSL install https://github.com/volkswagenfeature/nix-sync/tree/ffa6b78e7c9bfea96affb0da51847c7bfb11e493

**Comment by k4lipso** [comment] 2023-03-17 19:37
can confirm the same issue with nixpkgs/nixos-unstable. creating the symlink as mentioned by @volkswagenfeature worked for me.
still i have to point nvim to the correct config using `nvim -u /etc/nvim/sysinit.lua`

**Comment by alexjp** [comment] 2023-06-18 01:56
In my case, the runtime issue was fixed with commenting this line: https://github.com/pta2002/nixvim/blob/main/wrappers/nixos.nix#L35

**Comment by lumpsoid** [comment] 2023-06-23 09:43
same here
but non of the tricks here works for me
NixOS with flakes

```
{
    description = "lump";

    inputs = {
        nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
        home-manager.url = "github:nix-community/home-manager";
        home-manager.inputs.nixpkgs.follows = "nixpkgs";
	nixvim.url = github:pta2002/nixvim;
	nixvim.inputs.nixpkgs.follows = "nixpkgs";
    };

    outputs = inputs@{ nixpkgs, home-manager, nixvim, ... }: {
        nixosConfigurations = {
            qq = nixpkgs.lib.nixosSystem {
                system = "x86_64-linux";
                modules = [ 
                    ./configuration.nix 
                    home-manager.nixosModules.home-manager {
                        home-manager.useGlobalPkgs = true;
                        home-manager.useUserPackages = true;
                        home-manager.users.qq = import ./home.nix;
                    }
		    nixvim.nixosModules.nixvim {
		        programs.nixvim = {
		        	enable = true;
		        	options = {
		        		number = true;
		        		relativenumber = true;
		        		shiftwidth = 4;
		        		tabstop = 4;
		        	};
		        	plugins.oil.enable = true;
		        	plugins.lightline.enable = true;
		        	maps = {
		        		normal."-" = {
		        			action = "<cmd>require('oil').open";
		        		};
		        	};
		        };
		    }
                ];
            };
        };
    };
}
```
and I also have problem with infinite loop if I trying to call nixvim from ./home.nix

**Comment by ToyVo** [comment] 2023-06-23 23:52
> In my case, the runtime issue was fixed with commenting this line: https://github.com/pta2002/nixvim/blob/main/wrappers/nixos.nix#L35

Setting `wrapRc = true;` fixed this issue for me on nixos-unstable. My config worked just fine on nix-darwin and I noticed the darwin wrapper has wrapRc forced to true, so I guess I need true for both

**Comment by teto** [comment] 2023-06-24 14:58
wrapRc sets VIM which is used as VIMRUNTIME see `:h VIMRUNTIME`

**Closed** 2023-08-14 20:14 UTC
Labels: bug
