### ISSUE TITLE
csharp-ls can't find its references to load

### ISSUE THREAD

**Issue by loco-choco** [nix-community/nixvim#679] opened 2023-11-02 03:13 UTC
**Plugin affected**: csharp-ls
**Nixpkgs channel**: unstable
**Home-manager version**: master

## Description
After running neovim in a .cs file from a .net framework 4.8 project, it fails to load basic dependencies throwing unusable error warnings on the screen.

![image](https://github.com/nix-community/nixvim/assets/58634087/fcfe11f6-6788-4fd3-a8a6-8274eac13206)

Here are the `:messages` it returns:
```bash
LSP[csharp_ls][Info] csharp-ls: initializing, csharp-ls version 0.8.0.0; cwd: "/home/locochoco/rw-mods/pd-detection/pd-detection"             
LSP[csharp_ls][Info] csharp-ls: csharp-ls is released under MIT license and is not affiliated with Microsoft Corp.; see https://github.com/raz
zmatazz/csharp-language-server                                                                                                                
LSP[csharp_ls][Info] csharp-ls: MSBuildLocator: will register ".NET Core SDK", Version=7.0.403 as default instance                            
LSP[csharp_ls][Log] csharp-ls: attempting to find and load solution based on cwd ("/home/locochoco/rw-mods/pd-detection/pd-detection")..      
LSP[csharp_ls][Log] csharp-ls: 0 solution(s) found: []                                                                                        
LSP[csharp_ls][Log] csharp-ls: no or multiple .sln files found on /home/locochoco/rw-mods/pd-detection/pd-detection                           
LSP[csharp_ls][Log] csharp-ls: looking for .csproj/fsproj files on /home/locochoco/rw-mods/pd-detection/pd-detection..                        
LSP[csharp_ls][Log] csharp-ls: loading project "/home/locochoco/rw-mods/pd-detection/pd-detection/pd-detection.csproj"..                      
LSP[csharp_ls][Log] csharp-ls: OK, 1 project files loaded                                                                                     
LSP[csharp_ls][Log] csharp-ls: msbuildWorkspace.Diagnostics: [Failure] Msbuild failed when processing the file '/home/locochoco/rw-mods/pd-det
ection/pd-detection/pd-detection.csproj' with message: /nix/store/j5rfwd16fngw915jsxgdfr7009sda5fm-dotnet-core-combined/sdk/7.0.403/Microsoft.
Common.CurrentVersion.targets: (1241, 5): The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the
 Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs 
at https://aka.ms/msbuild/developerpacks                                                                                                      
LSP[csharp_ls][Log] csharp-ls: msbuildWorkspace.Diagnostics: [Warning] Unresolved metadata reference removed from project: /mscorlib.dll      
"PDDetection.cs" 86L, 3149B written   
```

I was able to get it to find the mscorlib dependencies by exporting `export FrameworkPathOverride=/nix/store/HASH-mono-6.12.0.182/lib/mono/4.8-api` before opening the file, but it kept not finding the other references, even though `msbuild` compiles the solution without an issue.

## Config
```nix
programs.nixvim = {
  enable = true;
  colorschemes.onedark = { 
    enable = true;
  };
  plugins.lightline.enable = true;
  plugins.coq-nvim.enable = true;
  plugins.lsp = {
    enable = true;
    servers = {
      nixd.enable = true;
      bashls.enable = true;
      clangd.enable = true;
      rust-analyzer.enable = true;
      csharp-ls.enable = true;
    };
  };
  plugins.nvim-cmp = {
    enable = true;
    completion.autocomplete = [ "TextChanged" ];
  };
};
```

**Comment by loco-choco** [comment] 2023-11-02 16:42
Update: exporting `export FrameworkPathOverride=/nix/store/HASH-mono-6.12.0.182/lib/mono/4.8-api` actually allowed it to find the references in some situations.

**Comment by GaetanLepage** [comment] 2023-11-02 22:52
Hmm weird. I am very unfamiliar with csharp.
If it happens to be caused by the plugin configuration (or fixable by nixvim) I would be glad to review/merge it.

**Comment by GaetanLepage** [comment] 2023-11-07 08:58
Could you try to replicate this bug in a non-nixvim (and even non-nix) environment ?
(Same config on a classically installed and configured neovim)

**Comment by loco-choco** [comment] 2023-11-07 14:38
I will try on a non nixvim enviroment. It also looks like there is a newer version of the ls that isn't on nixpkgs-unstable, so will also try that.

**Comment by GaetanLepage** [comment] 2023-11-07 15:00
I made a [PR](https://github.com/NixOS/nixpkgs/pull/266072) to update `csharp-ls`. I completely forgot that I was the maintainer for this !

**Comment by GaetanLepage** [comment] 2023-11-14 12:33
Could you please update your flake inputs and re-try ?
You should now get the latest version of `csharp-ls` (0.10.0).

**Comment by loco-choco** [comment] 2023-11-14 13:23
Still the same issue sadly.

![image](https://github.com/nix-community/nixvim/assets/58634087/41c1a262-5d47-42e9-9a1c-f71aaba0f354)

But I think I know why now, I guess it is an issue with dotnet msbuild not working well with .net framework projects in linux, cause it can't find the mono version of the assemblies.

![image](https://github.com/nix-community/nixvim/assets/58634087/10e9f97b-64fd-4adb-a78f-27422e40b5d4)

Maybe if there was a way to make it look for the mono assemblies, without breaking msbuild, it would make it work, because even on this "broken" state, it can still warn if you are calling a function from a 3rd library wrong.

**Comment by GaetanLepage** [comment] 2023-11-14 13:36
Ok, good to know.
Anyway, it is not related to nixvim nor the `csharp-ls` package in `nixpkgs`.
I will thus be closing this issue.
Good luck with it !

**Closed by GaetanLepage** 2023-11-14 13:36 UTC
Labels: bug

**Comment by loco-choco** [comment] 2023-11-14 23:52
I know the issue is closed, but just found a work around to use `dotnet build` with mono libraries, and wanted to have it here if someone finds themselves on the same situation.
Based on the solution in [here](https://andrewlock.net/building-net-framework-asp-net-core-apps-on-linux-using-mono-and-the-net-cli/), you can have a file called `netfx.props` in your project, with the contents:
```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <!-- When compiling .NET SDK 2.0 projects targeting .NET 4.x on Mono using 'dotnet build' you -->
    <!-- have to teach MSBuild where the Mono copy of the reference asssemblies is -->
    <TargetIsMono Condition="$(TargetFramework.StartsWith('net4')) and '$(OS)' == 'Unix'">true</TargetIsMono>
    
    <!-- Look in the standard install locations -->
    <BaseFrameworkPathOverrideForMono Condition="'$(BaseFrameworkPathOverrideForMono)' == '' AND '$(TargetIsMono)' == 'true' AND EXISTS('/Library/Frameworks/Mono.framework/Versions/Current/lib/mono')">/Library/Frameworks/Mono.framework/Versions/Current/lib/mono</BaseFrameworkPathOverrideForMono>
    <BaseFrameworkPathOverrideForMono Condition="'$(BaseFrameworkPathOverrideForMono)' == '' AND '$(TargetIsMono)' == 'true' AND EXISTS('/usr/lib/mono')">/usr/lib/mono</BaseFrameworkPathOverrideForMono>
    <BaseFrameworkPathOverrideForMono Condition="'$(BaseFrameworkPathOverrideForMono)' == '' AND '$(TargetIsMono)' == 'true' AND EXISTS('/usr/local/lib/mono')">/usr/local/lib/mono</BaseFrameworkPathOverrideForMono>

    <!-- If we found Mono reference assemblies, then use them -->
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net45'">$(BaseFrameworkPathOverrideForMono)/4.5-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net451'">$(BaseFrameworkPathOverrideForMono)/4.5.1-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net452'">$(BaseFrameworkPathOverrideForMono)/4.5.2-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net46'">$(BaseFrameworkPathOverrideForMono)/4.6-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net461'">$(BaseFrameworkPathOverrideForMono)/4.6.1-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net462'">$(BaseFrameworkPathOverrideForMono)/4.6.2-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net47'">$(BaseFrameworkPathOverrideForMono)/4.7-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net471'">$(BaseFrameworkPathOverrideForMono)/4.7.1-api</FrameworkPathOverride>
    <FrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != '' AND '$(TargetFramework)' == 'net48'">$(BaseFrameworkPathOverrideForMono)/4.8-api</FrameworkPathOverride>
    <EnableFrameworkPathOverride Condition="'$(BaseFrameworkPathOverrideForMono)' != ''">true</EnableFrameworkPathOverride>

    <!-- Add the Facades directory.  Not sure how else to do this. Necessary at least for .NET 4.5 -->
    <AssemblySearchPaths Condition="'$(BaseFrameworkPathOverrideForMono)' != ''">$(FrameworkPathOverride)/Facades;$(AssemblySearchPaths)</AssemblySearchPaths>
  </PropertyGroup>
</Project>
```
And import it on your .csproj with the `<Import Project="./netfx.props" />` line.
It should now allow `dotnet build` to find the build dependencies, and thus allow csharp-ls to work.
