### ISSUE TITLE
[BUG] Missing Line numbers on certain files

### ISSUE THREAD

**Issue by RoccoRakete** [nix-community/nixvim#1402] opened 2024-04-11 18:19 UTC
| Field        | Description |
|--------------|-------------|
| Nixpkgs      | `<unstable>` | 
| Home Manager | `<unstable>` | 

- [ x ] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Certain files are showing line numbers, others don't. I don't really know if it's a bug or a setting I can toggle, but I didn't find anything. 

Line numbers are enabled. 

![image](https://github.com/nix-community/nixvim/assets/44879342/cfde2354-9d8f-497c-b285-e8b28ea7bba7)

![image](https://github.com/nix-community/nixvim/assets/44879342/ac09e7e1-9a83-4f1b-921f-d13fd03ebbe3)

```nix

options = {
        number = true;
        relativenumber = false;
        shiftwidth = 2;
      };

```

**Comment by GaetanLepage** [comment] 2024-04-16 15:38
This is very weird indeed...
Can you try looking if `number`/`relativenumber` are actually enable when you are in a file where numbers are not showing ?
`:set number?`, `:set relativenumber?`

**Comment by GaetanLepage** [comment] 2024-04-17 10:54
My guess is that you have a plugin interfering with those settings.
Can you try limiting your config as most as possible and adding back the rest progressively ?

**Comment by RoccoRakete** [comment] 2024-04-17 11:12
It's getting weirder... 

If I'm opening the file from a commandline, the line numbers are showing. 
If I open them with neo-tree or telescope, they aren't.

**Comment by kevinsheth** [comment] 2024-05-03 19:53
@RoccoRakete  Try using "opts" instead of options.

**Comment by GaetanLepage** [comment] 2024-07-14 10:00
Any news on this @RoccoRakete ?

**Comment by ndean-bdaii** [comment] 2024-10-25 15:19
I also noticed this issue, where only certain files would show line numbers. I could only fix it by adding `programs.nixvim.extraConfigVim` section and under that section using `set number` all old-school style. I really wish that the old school vim settings could be set in a more nix-like way.

**Comment by ndean-bdaii** [comment] 2024-10-25 15:21
I will also add that many example configurations online have `programs.nixvim.globals.number=true;` or `programs.nixvim.globalOpts.number=true;` set, neither of which were consistent, but setting the `extraConfigVim` was completely consistent.

**Comment by ndean-bdaii** [comment] 2024-10-25 19:57
Okay, I think I figured it out. There is `opts`, `global`, and `globalOpts`. Turns out `opts` work the way I wanted it to work, and I missed this even though it is called out in the `README`, LOL. I wouldn't call this a bug but I would think that these three sections should be unified somehow, so that users don't go looking in multiple locations for a particular setting, especially because I couldn't seem to search for `opts` in the documentation search bar.

**Comment by GaetanLepage** [comment] 2024-10-26 23:24
> Okay, I think I figured it out. There is `opts`, `globals`, and `globalOpts`. Turns out `opts` work the way I wanted it to work, and I missed this even though it is called out in the `README`, LOL. I wouldn't call this a bug but I would think that these three sections should be unified somehow, so that users don't go looking in multiple locations for a particular setting, especially because I couldn't seem to search for `opts` in the documentation search bar.

Happy that you have figured it out in the end.
I completely get your point about unifying those as they are "similar".
However, I still think that they should remain top-level options. Indeed, nesting them into some `neovimOptions` meta-option feels too opinionated to me.
For me, `globals` (i.e. `vim.g.*`), `opts` (i.e. `vim.opt.*`), `globalOpts` (i.e. `vim.opt_global.*`)... are as distinct from each other as they are from `keymaps` or `autoCmd`.
For this reason, I feel like they should not be moved.
Also at this point, making such a drastic and breaking change for an eventual small clarity boost is not worth annoying all our users.

You can learn more about the neovim options in the [neovim documentation](https://neovim.io/doc/user/lua.html#lua-vim-options).

I will close this issue as it is indeed not a bug.
Thanks for having reported your issue and also shared your final understanding.

**Closed by GaetanLepage** 2024-10-26 23:24 UTC
Labels: bug
