### ISSUE TITLE
[BUG] enabling some lsp servers fails to build because of `vscode-langservers-extracted`

### ISSUE THREAD

**Issue by pinarruiz** [nix-community/nixvim#2051] opened 2024-08-21 18:45 UTC
| Field        | Description |
|--------------|-------------|
| Plugin       | `lsp` -> `eslint`, `html`, `jsonls`, `cssls`  | 
| Nixpkgs      | [`unstable (8a33541)`](https://github.com/NixOS/nixpkgs/tree/8a3354191c0d7144db9756a74755672387b702ba)  | 
| Home Manager | [`24.05 (e1391fb)`](https://github.com/nix-community/home-manager/tree/e1391fb22e18a36f57e6999c7a9f966dc80ac073) | 

- [X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

It seem the problem is with that upon enabling any of the servers that use `vscode-langservers-extracted` (as per [plugins/lsp/language-servers/default.nix](https://github.com/nix-community/nixvim/blob/b7f419a759f70126e220533b724cc17e8528b184/plugins/lsp/language-servers/default.nix)) makes the build process fail with:

```console
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[BABEL] Note: The code generator has deoptimised the styling of /build/resources/app/extensions/css-language-features/server/dist/node/cssServerMain.js as it exceeds the max of 500KB.
Successfully compiled 1 file with Babel (3435ms).
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[BABEL] Note: The code generator has deoptimised the styling of /build/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain.js as it exceeds the max of 500KB.
Successfully compiled 1 file with Babel (4128ms).
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Successfully compiled 1 file with Babel (2361ms).
babel:
  ../resources/app/extensions/markdown-language-features/server/dist/node does not exist
```

## Minimal, Reproducible Example (MRE)

Enabling any of the following will throw the error:

```nix
programs.nixvim.plugins.lsp = {
  enable = true;
  servers = {
    eslint.enable = true;
    html.enable = true;
    jsonls.enable = true;
    cssls.enable = true;
  };
}
```

---
I could not figure if this issue should be on [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs), but as I am using the package only for neovim, i figured it may belong here.

If any more feedback or config is required please let me know.

Thanks for your time.

**Comment by khaneliman** [comment] 2024-08-21 18:46
duplicate of https://github.com/nix-community/nixvim/issues/2043

**Comment by pinarruiz** [comment] 2024-08-21 18:47
> duplicate of #2043

Hi @khaneliman, 
Yeah i was coming here to close it as ypu where closing it, don't know how i didn't spot it -.-
Thanks anyway

**Closed by khaneliman** 2024-08-21 18:46 UTC
Labels: bug
