### ISSUE TITLE
[BUG] Docs for stable NixOS versions are missing from the upstream docs

### ISSUE THREAD

**Issue by rteats** [nix-community/nixvim#1485] opened 2024-05-02 23:05 UTC
| Field        | Description |
|--------------|-------------|
| Plugin       | `sleuth` `telescope`  | 
| Nixpkgs      | `23.11` | 
| Home Manager | `23.11` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When migrating from [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) to Nixvim, I faced an issue with rebuilding my home-manager configuration with the following outputs:
```
error: The option `programs.nixvim.plugins.telescope.extensions.ui-select' does not exist.
error: The option `programs.nixvim.plugins.sleuth' does not exist.
```
There were also other options that needed a `-nvim` suffix in order to work (`comment-nvim`, for example). Here's my [configuration](https://github.com/rteats/nixos-config), if that cam be useful.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    plugins = {
      sleuth.enable = true;
      telescope.enable = true;
      telescope.extensions.ui-select.enable = true;
    };
}
```

**Comment by traxys** [comment] 2024-05-03 06:38
I believe these options are not availaible on the 23.11 branch of nixvim, we did many refactors recently

**Comment by MattSturgeon** [comment] 2024-05-03 07:37
Currently we only have docs available for tha main branch (targeting nixos-unstable), which can be confusing when there are differences.

You could try doing `nix build github:nix-community/nixvim/nixos-23.11#docs` to build 23.11 docs locally.

(I'll edit this when I get to a PC and test the command, posting from my phone)

**Comment by rteats** [comment] 2024-05-03 12:30
> I believe these options are not availaible on the 23.11 branch of nixvim, we did many refactors recently

You're right, on nixos-23.11 branch there are much fewer plugins and the ones I listed simply don't exist.

> You could try doing `nix build github:nix-community/nixvim/nixos-23.11#docs` to build 23.11 docs locally.

Sounds like the last reason to start using an unstable channel for me. :) Going to do this now.

This issue is more about the lack of docs for nixos-23.11, so I'll change its name accordingly.

**Comment by MattSturgeon** [comment] 2024-05-03 13:42
Duplicate of #1223

**Closed by MattSturgeon** 2024-05-03 13:42 UTC
Labels: bug
