### ISSUE TITLE
IBL not loading correctly

### ISSUE THREAD

**Issue by AlecsFerra** [nix-community/nixvim#666] opened 2023-10-23 19:14 UTC
**Plugin affected**: What plugin does this bug relate to (if applicable) indent-blank-line
**Nixpkgs channel**: Either unstable or your nixos version unstable
**Home-manager version**: (if applicable)
unstable

## Description
enable ibl
on startup you will get
Error detected while processing /home/alecs/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/alecs/.config/nvim/init.lua:60: module 'ibl' not found:
        no field package.preload['ibl']

## Config
Your nixvim config https://github.com/AlecsFerra/nix-machine/tree/master/nixos/user/nvim

**Comment by GaetanLepage** [comment] 2023-10-23 20:50
Can you try to update your flake inputs ?
`indent-blankline` has been updated very recently on `nixos-unstable`. The versions before will throw the error you mention.

**Comment by AlecsFerra** [comment] 2023-10-24 08:35
I'm not using flakes, and from https://status.nixos.org/ unstable hasen't been successfully build in 4 days

**Comment by evccyr** [comment] 2023-10-24 12:33
I'm facing the same issue where I recently installed IBL and need to manually enable it with the command.

**Comment by GaetanLepage** [comment] 2023-10-24 12:40
> I'm not using flakes, and from https://status.nixos.org/ unstable hasen't been successfully build in 4 days

`nixos-unstable` has received the update for `indent-blankline`.
I have no issue when testing with a flake.
You should not have any problems either even if you are using channels the classic way...
I haven't checked if the update has landed on the `nixpkgs-unstable` channel though.

**Comment by GaetanLepage** [comment] 2023-10-28 15:49
@AlecsFerra @evccyr do you still encounter the issue ?

**Comment by AlecsFerra** [comment] 2023-10-29 00:05
Got worst

`error: attribute 'fantomas' missing`

**Comment by AlecsFerra** [comment] 2023-10-29 00:20
Loaded a previous commit than this fantomas issue and is still not working

**Comment by GaetanLepage** [comment] 2023-10-30 09:16
It really looks like an out-of-sync nixpkgs compared to nixvim.
Can you try to run `nix-build -E "with import <nixpkgs> {}; pkgs.vimPlugins.indent-blankline-nvim"` ?

**Comment by evccyr** [comment] 2023-10-30 21:10
fixed for me

**Comment by mmartinortiz** [comment] 2023-11-01 07:53
I also get the `error: attribute 'fantomas' missing` error. In my case, on WSL. @GaetanLepage last tip did not solved it.

**Comment by GaetanLepage** [comment] 2023-11-01 08:40
Last tip was to know which version of IBL it would build.
Could you reproduce it and tell me which version comes out ?

**Comment by mmartinortiz** [comment] 2023-11-01 08:48
> Could you reproduce it and tell me which version comes out ?

/nix/store/yv0djcqd7k7r72whkgfyfink8pl80jk8-vimplugin-indent-blankline.nvim-2023-10-23

**Comment by GaetanLepage** [comment] 2023-11-01 08:54
I don't get why fantomas would be causing you trouble... Do you have `none-ls` enabled ?
Is the `plugins.none-ls.sources.formatting.fantomas.enable` option set to `true` ?

**Comment by GaetanLepage** [comment] 2023-11-01 08:58
Also,
- How are you running Nixvim ?
  - Standalone flake
  - Home-manager module
  - NixOS module
- Are you using a flake or the classic nix-channel ?

**Comment by mmartinortiz** [comment] 2023-11-01 09:07
> Do you have `none-ls` enabled ? Is the `plugins.none-ls.sources.formatting.fantomas.enable` option set to `true` ?

No, it is `null-ls` the one I [have enabled](https://github.com/mmartinortiz/nix-conf/blob/main/home/console/neovim/config/lsp.nix#L62)

> How are you running Nixvim?

Via [Home-manager module](https://github.com/mmartinortiz/nix-conf/blob/main/flake.nix#L36), using a flake.

The configuration I pointed is my public one, I'm using that as base for my setup at work, where I use WSL. Here is how I load Nixvim as module and then import my public config.

```nix
{
  description = "My Home Manager flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-config.url = "github:mmartinortiz/nix-conf";
    nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    nixpkgs,
    home-manager,
    home-config,
    nixvim,
    ...
  }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    homeConfigurations.myuser = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          nixvim.homeManagerModules.nixvim
          (home-config + "/home")
          ./home
        ];
    };
  };
}
```

When I run `home-manager switch --flake .` is when I get the error about `fantomas`, what does not happen in my Ubuntu machines.

**Comment by GaetanLepage** [comment] 2023-11-01 09:24
> No, it is `null-ls` the one I [have enabled](https://github.com/mmartinortiz/nix-conf/blob/main/home/console/neovim/config/lsp.nix#L62)

We have replaced `null-ls` with `none-ls` as the former as been archived.
Normally, all of your options should work as before.

**Comment by GaetanLepage** [comment] 2023-11-01 09:25
Could you try once more to update your flake inputs ?

**Comment by mmartinortiz** [comment] 2023-11-01 09:58
I changed `null-ls` by `none-ls`. I can [clearly see](https://nix-community.github.io/nixvim/plugins/none-ls/index.html) that `none-ls` is an available plugin.

Ubuntu machine: "The option `programs.nixvim.plugins.none-ls` does not exist"

WSL: Same error about `fantomas`

In both cases I run `nix-index --update`, `nix-store --gc` and removed the `~/.cache/nix` folder. I guess that I'm doing something basic wrong :-/

**Comment by GaetanLepage** [comment] 2023-11-01 10:03
You clearly have an older revision of nixvim. `null-ls` does not exist in nixvim anymore.
To udpate your flake inputs, the command is `nix flake update` (to run from the git repository where your `flake.nix` lives).
This will fetch all of the repos mentioned in the `inputs` section of your flake and pin those changes in your `flake.lock` (which will change).

**Comment by mmartinortiz** [comment] 2023-11-01 10:22
`nix flake update` is my new favourite `nix` command :D . Flakes updated and I get a new warning about `keymaps` that I will address in the future.

The Ubuntu machine switches to the configuration nicely. The WSL returns an error about conflicting values

```
error: The option `home.username' has conflicting definition values:
- In `/nix/store/8hixnlm22sfa74x1lgi1z52xz7mhm7ca-source/home': "myworkuser"
- In `/nix/store/syxvzhvhiwyzz539jh3aymwryj2sqpqb-source/home': "myhomeuser"
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

But that is a different issue :)

**Comment by GaetanLepage** [comment] 2023-11-01 10:24
Good ! This is indeed how you have to update your HM config (packages, etc)

I am pretty sure that you are in the same case @AlecsFerra.
I will wait for your confirmation before closing the issue.

**Comment by AlecsFerra** [comment] 2023-11-01 12:55
Also using a revision older than the fantomas one and newer than the ibl update i still get the ibl loading error

**Comment by wvffle** [comment] 2023-11-06 06:28
Upgrading my nixos machine with `nixos-rebuild switch --upgrade` and then running `home-manager switch` did the trick for me.

**Comment by GaetanLepage** [comment] 2023-11-06 06:51
I will be closing this issue as it is not a nixvim bug.
If you encounter such behavior, please double-check whether your nixpkgs and nixvim channels/flake inputs have been properly updated.

**Closed by GaetanLepage** 2023-11-06 06:51 UTC
Labels: bug
