### ISSUE TITLE
"The option is used but not defined" on nix-darwin

### ISSUE THREAD

**Issue by adrianord** [nix-community/nixvim#66] opened 2022-11-14 18:20 UTC
**Nixpkgs channel**: master
**Home-manager version**: master

## Description
When trying to use this module at all, I get the following error message
```
building the system configuration...
error: The option `home-manager.users.aordonez.programs.nixvim' is used but not defined.
(use '--show-trace' to show detailed location information)
```
Even with a very simple `flake.nix` which I will supply below.

Not sure if I'm doing something wrong on my side, but from referencing other people's nix configs who are using this flake on nixos, I don't believe I'm doing anything differently other than being on macos

## Config
```nix
{
  description = "";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/master";

    darwin.url = "github:lnl7/nix-darwin/master";
    darwin.inputs.nixpkgs.follows = "nixpkgs";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nixvim.url = "github:pta2002/nixvim";
  };

  outputs = { self, nixpkgs, darwin, home-manager, ... }@inputs:
    {
      darwinConfigurations.gon = darwin.lib.darwinSystem {
        system = "aarch64-darwin";
        specialArgs = { inherit inputs; };
        modules = [
          home-manager.darwinModules.home-manager
          {
            nix.extraOptions = ''
              experimental-features = nix-command flakes
            '';
          }
          {
            users.users.aordonez = {
              name = "aordonez";
            };
            home-manager.users.aordonez = {

              home.stateVersion = "22.11";
              imports = [ inputs.nixvim.homeManagerModules.nixvim ];
            };
          }
        ];
      };
    };
}
```

**Comment by pta2002** [comment] 2022-11-15 11:15
Ah damn I can try to fix this but it'll be incredibly hard for me to debug because I don't own a mac :/

**Comment by volkswagenfeature** [comment] 2022-11-28 19:58
I have had this bug as well on NixOS. I discovered that installing, but not activating this package does not work properly. Adding `programs.nixvim.enable=true` let my flake build.

**Comment by adrianord** [comment] 2022-11-30 23:36
Thanks @volkswagenfeature, it seems as much as defining `programs.nixvim = {};` is enough to resolve the error.

**Comment by volkswagenfeature** [comment] 2022-12-02 04:43
> Thanks @volkswagenfeature, it seems as much as defining `programs.nixvim = {};` is enough to resolve the error.

Can confirm this is the case on NixOS too.

**Comment by gaetgu** [comment] 2022-12-27 18:56
I can also confirm that setting `program.nixvim` to anything resolves this issue. You can probably mark this as closed, then, (and maybe add something to the readme? even just a link pointing to this issue)

**Comment by pta2002** [comment] 2022-12-29 13:21
Yeah this is an issue I've had before and I haven't been able to figure out what's causing it. I'll need to look into it better.

**Comment by pta2002** [comment] 2023-06-06 00:14
Hey, can anyone confirm if this is still an issue? I have a vague idea of a similar issue having been fixed on other platforms, so if it's fixed I'd like to close this :)

**Comment by GaetanLepage** [comment] 2023-07-13 06:19
I was not able to reproduce on NixOS.
Adding the module without specifying any configuration (not even `programs.nixvim.enable = true`) is working fine.

Could someone try again on darwin ?

**Comment by GaetanLepage** [comment] 2023-07-17 21:09
Ok, thank you @fabianpage for testing.
I will close this issue as we are not able to reproduce this bug.
Feel free to reopen/complain if this happens again.

**Closed by GaetanLepage** 2023-07-17 21:09 UTC
Labels: bug
